@startuml

' Настройка стиля для прямоугольника
skinparam class {
    BackgroundColor #FFF
    BorderColor #000
    ArrowColor #000
    FontName Arial
}

' Класс с атрибутами и методами

class "Учебный план" as учебныйплан {
  ' Атрибуты (поля класса)
  - Просмотр индивидуального учебного плана
  - информация о дисциплинах
 

 ' Методы (функции класса)

  + ()-

}

' Можно добавить связь с другим классом (опционально)
' class AnotherClass
' MyClass --> AnotherClass : "использует"
учебныйплан--Зачетнаякнижка



' Настройка стиля для прямоугольника
skinparam class {
    BackgroundColor #FFF
    BorderColor #000
    ArrowColor #000
    FontName Arial
}

' Класс с атрибутами и методами

class "Зачетная книжка" as Зачетнаякнижка {
  ' Атрибуты (поля класса)
  - Просмотр дисциплин, оценок, кол-ва часов, ФИО преподавателей

  ' Методы (функции класса)
  +()Выбрать год,семестр
  +()Выгрузить в pdf-файл
  +() Копирование ссылки, генерация новой ссылки
}

' Можно добавить связь с другим классом (опционально)
' class AnotherClass
' MyClass --> AnotherClass : "использует"
' Можно добавить связь с другим классом (опционально)
' class AnotherClass
' MyClass --> AnotherClass : "использует"
учебныйплан--Экзаменационныйлист

' Настройка стиля для прямоугольника
skinparam class {
    BackgroundColor #FFF
    BorderColor #000
    ArrowColor #000
    FontName Arial
}

' Класс с атрибутами и методами
class "Экзаменационный лист" as Экзаменационныйлист {
  ' Атрибуты (поля класса)
  -  Формирование экзаменационного листа по отдельной дисциплине
 
  ' Методы (функции класса)
  + ()Просмотр пересдач и задолженностей 
  + () Просмотр результатов экзаменов
}

' Можно добавить связь с другим классом (опционально)
' class AnotherClass
' MyClass --> AnotherClass : "использует"

' Класс с атрибутами и методами
class "Практика" as Практика {
  ' Атрибуты (поля класса)
  - ФИО студента
  - Инструкция
  - Шаблон документов
  - Скан документов
  - Список предприятий
  - Список руководителей
  - Список тем
  ' Методы (функции класса)
  + (): Просмотр и скачивание инструкции
  + (): Переход на страницу с информацией
  + (): выбор предприятия, руководителя, темы
  + (): Открыть шаблон документов
  + (): Добавить скан документов
}

' Можно добавить связь с другим классом (опционально)
' class AnotherClass
' MyClass --> AnotherClass : "использует"
Практика--БРС

' Настройка стиля для прямоугольника
skinparam class {
    BackgroundColor #FFF
    BorderColor #000
    ArrowColor #000
    FontName Arial
}

' Класс с атрибутами и методами
class "БРС" as БРС {
  ' Атрибуты (поля класса)
  - Название дисциплины
  - ФИО преподавателя
  - Итоги по дисциплине
  - Общий балл за лекции
  - Общий балл за практики
  - Текущая аттестация по лекции
  - Текущая аттестация по практике
  - Промежуточная аттестация по лекции
  - Промежуточная аттестация по практике
  - Коэффиценты
  ' Методы (функции класса)
  + (): Просмотр баллов
  + (): Анализ успеваемости
  + (): Анализ динамики успеваемости
}
' Можно добавить связь с другим классом (опционально)
' class AnotherClass
' MyClass --> AnotherClass : "использует"

' Класс с атрибутами и методами
class "Курсовое проектирование" as Курсовоепроектирование {
  ' Атрибуты (поля класса)
  - График курсовых работ
  - Дисциплина, модуль
  ' Методы (функции класса)
  + (): Загрузить файл отчета 
  + (): Загрузить файл рецензии
} 
class "ЭБС" as ЭБС {
  ' Атрибуты (поля класса)
  - Учебно-методические материалы
  - Электронная библиотека
  ' Методы (функции класса)
  + (): Согласие на обработку перс. данных
  + (): Возможность перехода на университетскую бибилиотеку онлайн
  + (): Возможность перехода на IPR boors
  + (): Навигация
}
' Можно добавить связь с другим классом (опционально)
' class AnotherClass
' MyClass --> AnotherClass : "использует"
ЭБС--Порталинформационнообразовательныхресурсов

' Класс с атрибутами и методами
class "Цифровая кафедра УрФУ" as ДПОУрФУ {
  ' Атрибуты (поля класса)
  - Переход на страницу авторизации/регистрации
  - Ввод логина и пароля
  ' Методы (функции класса)
  + (): Возможность запоминания введенных данных
  + (): Меню (программы, студентам УрФУ, преподавателям, сотрудникам предприятий, лк, выход)
  + (): Выбор образования (проф подготовка, повышение квалификации, доп образование, стажировка, корпоративное обучение, спец предложения)
  + (): Просмотр и ознакомление с представленными программами
  + (): Поиск подходящей программы по параметрам (направление, тип программы, для кого, формат, документ)
  + (): Пошаговая инструкция по записи на программу с соответствующими ссылками
  + (): Обратная связь (консультация)
}
' Можно добавить связь с другим классом (опционально)
' class AnotherClass
' MyClass --> AnotherClass : "использует"

' Класс с атрибутами и методами
class "Портал информационно-образовательных ресурсов" as Порталинформационнообразовательныхресурсов{
  ' Атрибуты (поля класса)
  - Ресурсы ОП
  - Каталог ресурсов
  - Зональная научная библиотека
  ' Методы (функции класса)
  + (): Доступ к образовательным материалам
  + (): Доступ к платформам внешних обраловательных ресурсов
  + (): Система поиска и фильтрации
  + (): Быстрый доступ в зональную библиотеку
  + (): Просмотр баллов
  + (): Анализ успеваемости
  + (): Анализ динамики успеваемости
}
' Можно добавить связь с другим классом (опционально)
' class AnotherClass
' MyClass --> AnotherClass : "использует"
Курсовоепроектирование -- учебныйплан

' Класс с атрибутами и методами
class "Методическое обеспечение образовательной программы" as Методическоеобеспечениеобразовательнойпрограммы {
  ' Атрибуты (поля класса)
  - Учебно-методические документы
  - Системное описание образовательного процесса, которое будет реализовано на практике
  ' Методы (функции класса)
  + (): Просмотр и скачивание материалов
  + (): Обратная связь с преподавателями
  + (): Просмотр индивидуального учебного плана
  + (): Доступ к методическим материалам и рекомендациям по обучению
  + ():Дополнительные ресурсы для самостоятельного обучения 
}
' Можно добавить связь с другим классом (опционально)
' class AnotherClass
' MyClass --> AnotherClass : "использует"
Методическоеобеспечениеобразовательнойпрограммы -- Экзаменационныйлист

' Настройка стиля для прямоугольника
skinparam class {
    BackgroundColor #FFF
    BorderColor #000
    ArrowColor #000
    FontName Arial
}

' Класс с атрибутами и методами

class "Общий рейтинг студента" as Общийрейтинг {
  ' Атрибуты (поля класса)
  - Личный рейтинг
  - Рейтинг за период: позиция, фио, институт, балл
  - Информация об устройстве системы расчёта рейтинга
  - Документация

  ' Методы (функции класса)
  +(): Выбрать группу, семестр, год
  +(): Переход по ссылкам (иные сервисы УрФУ, почты для связи, документация)
  +(): Просмотр и скачивание документации
}
' Можно добавить связь с другим классом (опционально)
' class AnotherClass
' MyClass --> AnotherClass : "использует"
Общийрейтинг -- БРС

' Настройка стиля для прямоугольника
skinparam class {
    BackgroundColor #FFF
    BorderColor #000
    ArrowColor #000
    FontName Arial
}

' Класс с атрибутами и методами

class "Modeus" as Modeus {
  ' Атрибуты (поля класса)
  - Расписание
  - Оценки
  - Выбор модулей
  - Справочная информация
  

  ' Методы (функции класса)
  +(): Выбор дня/недели/месяца, расписания звонков
  +(): Просмотр и открытие информации о мероприятиях
  +(): Переход по ссылке "адреса корпусов"
  +(): Печать календаря
  +(): Скачивание в формате iCal
  +(): Выгрузить оценки в Exel
  +(): Выбор периода
  +(): Поиск модуля, сортировка по завершенности, алфавиту, дате начала/окончания, кол-ву мест
  +(): Переход по страницам сайта (рейтинги, расписание, выбор модулей)
  +(): Просмотр инструкции по работе с площадкой
}
' Можно добавить связь с другим классом (опционально)
' class AnotherClass
' MyClass --> AnotherClass : "использует"
Modeus -- учебныйплан
Modeus -- Зачетнаякнижка
Modeus -- БРС
@enduml
