@startuml

' Настройка стиля для прямоугольника
skinparam class {
    BackgroundColor #FFF
    BorderColor #000
    ArrowColor #000
    FontName Arial
}

' Класс с атрибутами и методами

class "Учебный план" as учебныйплан {
  ' Атрибуты (поля класса)
  - Просмотр индивидуального учебного плана
  - информация о дисциплинах
 

 ' Методы (функции класса)

  + ()-

}

' Можно добавить связь с другим классом (опционально)
' class AnotherClass
' MyClass --> AnotherClass : "использует"
учебныйплан--Зачетнаякнижка



' Настройка стиля для прямоугольника
skinparam class {
    BackgroundColor #FFF
    BorderColor #000
    ArrowColor #000
    FontName Arial
}

' Класс с атрибутами и методами

class "Зачетная книжка" as Зачетнаякнижка {
  ' Атрибуты (поля класса)
  - Просмотр дисциплин, оценок, кол-ва часов, ФИО преподавателей

  ' Методы (функции класса)
  +()Выбрать год,семестр
  +()Выгрузить в pdf-файл
  +() Копирование ссылки, генерация новой ссылки
}

' Можно добавить связь с другим классом (опционально)
' class AnotherClass
' MyClass --> AnotherClass : "использует"
' Можно добавить связь с другим классом (опционально)
' class AnotherClass
' MyClass --> AnotherClass : "использует"
учебныйплан--Экзаменационныйлист

' Настройка стиля для прямоугольника
skinparam class {
    BackgroundColor #FFF
    BorderColor #000
    ArrowColor #000
    FontName Arial
}

' Класс с атрибутами и методами
class "Экзаменационный лист" as Экзаменационныйлист {
  ' Атрибуты (поля класса)
  -  Формирование экзаменационного листа по отдельной дисциплине
 
  ' Методы (функции класса)
  + ()Просмотр пересдач и задолженностей 
  + () Просмотр результатов экзаменов
  + () Ghjcvjnh xtuj

}

' Можно добавить связь с другим классом (опционально)
' class AnotherClass
' MyClass --> AnotherClass : "использует"g

' Класс с атрибутами и методами
class "Практика" as Практика {
  ' Атрибуты (поля класса)
  - ФИО студента
  - Инструкция
  - Шаблон документов
  - Скан документов
  - Список предприятий
  - Список руководителей
  - Список тем
  ' Методы (функции класса)
  + (): Просмотр и скачивание инструкции
  + (): Переход на страницу с информацией
  + (): выбор предприятия, руководителя, темы
  + (): Открыть шаблон документов
  + (): Добавить скан документов
}

' Можно добавить связь с другим классом (опционально)
' class AnotherClass
' MyClass --> AnotherClass : "использует"
Практика--БРС

' Настройка стиля для прямоугольника
skinparam class {
    BackgroundColor #FFF
    BorderColor #000
    ArrowColor #000
    FontName Arial
}

' Класс с атрибутами и методами
class "БРС" as БРС {
  ' Атрибуты (поля класса)
  - Название дисциплины
  - ФИО преподавателя
  - Итоги по дисциплине
  - Общий балл за лекции
  - Общий балл за практики
  - Текущая аттестация по лекции
  - Текущая аттестация по практике
  - Промежуточная аттестация по лекции
  - Промежуточная аттестация по практике
  - Коэффиценты
  ' Методы (функции класса)
  + (): Просмотр баллов
  + (): Анализ успеваемости
  + (): Анализ динамики успеваемости
}
' Можно добавить связь с другим классом (опционально)
' class AnotherClass
' MyClass --> AnotherClass : "использует"

' Класс с атрибутами и методами
class "Модеус" as Модеус {
  ' Атрибуты (поля класса)
  - Название дисциплины
  - ФИО преподавателя
  - Итоги по дисциплине
  - Общий балл за лекции
  - Общий балл за практики
  - Текущая аттестация по лекции
  - Текущая аттестация по практике
  - Промежуточная аттестация по лекции
  - Промежуточная аттестация по практике
  - Коэффиценты
  ' Методы (функции класса)
  + (): Просмотр баллов
  + (): Анализ успеваемости
  + (): Анализ динамики успеваемости
}
' Можно добавить связь с другим классом (опционально)
' class AnotherClass
' MyClass --> AnotherClass : "использует"
@enduml